" =============================================================================
" wenhao
" =============================================================================

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

" -----------------------------------------------------------------------------
"  < 基础配置 >
" -----------------------------------------------------------------------------
set encoding=utf-8
set clipboard^=unnamed,unnamedplus
set mouse=a
set hidden                                      "允许切换缓冲区
set autoread                                    "自动加载该文件外部修改

" -----------------------------------------------------------------------------
"  < 文件配置 >
" -----------------------------------------------------------------------------
filetype plugin indent on                       "启用文件类型侦测,加载对应的插件,启用缩进
set fileencodings=utf-8,gbk,latin1

set autoindent                                  "自动缩进
set expandtab                                   "将Tab键转换为空格
set tabstop=4                                   "设置Tab键的宽度
set shiftwidth=4                                "换行时自动缩进宽度
set softtabstop=4                               "按Tab插入空格

" -----------------------------------------------------------------------------
"  < 界面配置 >
" -----------------------------------------------------------------------------
syntax on                                       "语法高亮
set number                                      "显示行号
set showmode                                    "显示模式
set showcmd                                     "显示命令
set cursorline                                  "突出显示当前行
set laststatus=2                                "启用状态栏信息
"set cmdheight=2                                 "设置命令行的高度为2，默认为1
"set guifont=Consolas:h12               	     "设置字体:字号
set nowrap                                      "设置不自动换行
"set shortmess=atI                               "去掉欢迎界面
"set colorcolumn=100                             "行长参考线
set guioptions-=m                               "隐藏菜单栏
set guioptions-=T                               "隐藏工具栏

set scrolloff=5                                 "垂直滚动时光标偏移
set sidescrolloff=5                             "水平滚动时光标偏移

set ignorecase                                  "搜索模式里忽略大小写
set smartcase                                   "搜索模式包含大写字符，不使用'ignorecase'选项
set incsearch                                   "启用实时搜索高亮
set hlsearch                                    "高亮所有匹配项

set statusline+=%F%m%r%h%w\ [%{&ff}]\ [%Y]%=[%04l,%04v][%p%%][%04L]

set termguicolors
colorscheme habamax                             "desert habamax retrobox

" -----------------------------------------------------------------------------
"  < 按键配置 >
" -----------------------------------------------------------------------------
let mapleader=' '

nnoremap <Leader>h gT
nnoremap <Leader>l gt

nnoremap <Leader>q :q<CR>
nnoremap <Leader>Q :qa!<CR>

inoremap jj <Esc>

inoremap <C-h> <Left>
inoremap <C-l> <Right>
inoremap <C-k> <Up>
inoremap <C-j> <Down>

" -----------------------------------------------------------------------------
"  < 其它配置 >
" -----------------------------------------------------------------------------
"set writebackup                                 "保存文件前建立备份，保存成功后删除该备份
set noundofile                                  "无un文件
set nobackup                                    "设置无备份文件
set noswapfile                                  "设置无临时文件
"set vb t_vb=                                    "关闭提示音

autocmd FocusGained,BufEnter * checktime        "文件变更检测
